# This file was automatically generated by RASC

set(RASC_TARGET_DEVICE R9A07G075M24_CPU0)
set(RASC_TARGET_ARCH cortex-r52)
set(RASC_PROJECT_NAME MESC_RZT2M)
set(RASC_TOOLCHAIN_NAME, GCC)

SET(RASC_CMAKE_CXX_FLAGS "-g -O0 -mcpu=cortex-r52 -I ${CMAKE_CURRENT_LIST_DIR}/../../MESC_Common -I ${CMAKE_CURRENT_LIST_DIR}/../../MESC_Common/Inc -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/arm/CMSIS_5/CMSIS/Core_R/Include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/aws/amazon-freertos/freertos_kernel/include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/aws/amazon-freertos/libraries/freertos_plus/standard/freertos_plus_tcp/include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc/api -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc/instances -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/src/rm_freertos_plus_tcp -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/src/rm_freertos_port -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/aws -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/fsp_cfg -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/fsp_cfg/bsp -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_gen -I ${CMAKE_CURRENT_LIST_DIR}/../src  -D_RZT_CORE=CR52_0  -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -mthumb  -std=c99 -MMD -MP -MF <SOURCE>.d -MT <OBJECT>")

SET(RASC_CMAKE_ASM_FLAGS "-g -O0 -mcpu=cortex-r52 -I ${CMAKE_CURRENT_LIST_DIR}/../../MESC_Common -I ${CMAKE_CURRENT_LIST_DIR}/../../MESC_Common/Inc -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/arm/CMSIS_5/CMSIS/Core_R/Include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/aws/amazon-freertos/freertos_kernel/include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/aws/amazon-freertos/libraries/freertos_plus/standard/freertos_plus_tcp/include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc/api -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc/instances -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/src/rm_freertos_plus_tcp -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/src/rm_freertos_port -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/aws -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/fsp_cfg -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/fsp_cfg/bsp -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_gen -I ${CMAKE_CURRENT_LIST_DIR}/../src  -D_RZT_CORE=CR52_0  -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -mthumb   -x assembler-with-cpp -MMD -MP")

SET(RASC_CMAKE_C_FLAGS "-g -O0 -mcpu=cortex-r52 -I ${CMAKE_CURRENT_LIST_DIR}/../../MESC_Common -I ${CMAKE_CURRENT_LIST_DIR}/../../MESC_Common/Inc -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/arm/CMSIS_5/CMSIS/Core_R/Include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/aws/amazon-freertos/freertos_kernel/include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/aws/amazon-freertos/libraries/freertos_plus/standard/freertos_plus_tcp/include -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc/api -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/inc/instances -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/src/rm_freertos_plus_tcp -I ${CMAKE_CURRENT_LIST_DIR}/../rzt/fsp/src/rm_freertos_port -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/aws -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/fsp_cfg -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_cfg/fsp_cfg/bsp -I ${CMAKE_CURRENT_LIST_DIR}/../rzt_gen -I ${CMAKE_CURRENT_LIST_DIR}/../src  -D_RZT_CORE=CR52_0  -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -mthumb  -std=c99 -MMD -MP -MF <SOURCE>.d -MT <OBJECT>")

SET(RASC_CMAKE_EXE_LINKER_FLAGS "-g -O0 -mcpu=cortex-r52 -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -mthumb -T fsp.ld -Xlinker --gc-sections -Wl,-Map,${PROJECT_NAME}.map --specs=nano.specs --specs=rdimon.specs -L ${CMAKE_CURRENT_LIST_DIR}/../ -L ${CMAKE_CURRENT_LIST_DIR}/../script  -o ${CMAKE_CURRENT_LIST_DIR}/../build/CMakeFiles/${RASC_PROJECT_NAME}.elf.dir/${RASC_PROJECT_NAME}.elf")

SET(RASC_CMAKE_DEFINITIONS "_RENESAS_RZT_;_RZT_CORE=CR52_0;_RZT_ORDINAL=1")

SET(RASC_ASM_FILES "${CMAKE_CURRENT_LIST_DIR}/../rzt_gen/*.asm")

# ADD COMPILE FLAGS FOR GCC version >= 12.2
if (CMAKE_C_COMPILER_ID STREQUAL "GNU" AND CMAKE_C_COMPILER_VERSION VERSION_GREATER_EQUAL 12.2)
    list(INSERT RASC_CMAKE_C_FLAGS 0 "--param=min-pagesize=0;-Wno-format-truncation;-Wno-stringop-overflow")
    list(INSERT RASC_CMAKE_CXX_FLAGS 0 "--param=min-pagesize=0;-Wno-format-truncation;-Wno-stringop-overflow")
endif()

SET(RASC_DEBUG_FLAGS "-g;-O2")
SET(RASC_RELEASE_FLAGS "-O2")
SET(RASC_MIN_SIZE_RELEASE_FLAGS "-Os")
SET(RASC_RELEASE_WITH_DEBUG_INFO "-g;-O2")

# Custom targets are defined below
include_guard()

# Create platform-specific command line for running Smart Configurator as a backgrounded
# process, which avoids blocking any calling IDEs
file(TO_NATIVE_PATH "${RASC_EXE_PATH}" RASC_EXE_NATIVE_PATH)
if(CMAKE_HOST_WIN32)
    set(RASC_COMMAND start "" /b "${RASC_EXE_NATIVE_PATH}" configuration.xml)
else()
    set(RASC_COMMAND sh -c \"${RASC_EXE_NATIVE_PATH} configuration.xml &\")
endif()

# Make target for opening the FSP Configuration in Smart Configurator
add_custom_target(rasc
    COMMAND ${RASC_COMMAND}
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    COMMENT "FSP Smart Configurator"
)
