name: CMake

on:
  workflow_dispatch:
  push:
    branches: [ "MESC_HAL", "master" ]
  pull_request:
    branches: [ "MESC_HAL", "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  github-build:
    runs-on: ubuntu-latest
    steps:

      - name: Install LLVM & Ninja
        run: |
          sudo apt install clang-format clang-tidy ninja-build ccache

      - name: Install ARM toolchain
        run: |
          echo "Downloading toolchain..."
          wget -q --no-check-certificate https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          echo "Unpacking toolchain"
          sudo tar -xjf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 -C /usr/share/
          echo "Creating symlinks"
          sudo ln -s /usr/share/gcc-arm-none-eabi-10.3-2021.10/bin/* /usr/bin/

      - name: Checkout Files
        uses: actions/checkout@v3

      - name: Build Init
        run: |
          cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=rzt.cmake

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: output
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ${{github.workspace}}/build/*.elf
            ${{github.workspace}}/build/*.bin
            ${{github.workspace}}/build/*.hex
